name: Keep Server Alive

on:
  schedule:
    - cron: "*/2 * * * *"  # Runs every 2 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  ping_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # - name: Install dependencies (if required)
      #   run: npm install || true  # Skip if no package.json

      - name: Run ping script
        run: node ping_my_server.js
